'------------------------------------------------------------------------------
' Project:      Digital Logic Adders
' Module:       Outputs
' File:         Outputs.bas
'
' Description:
'     Computes the expected output values for a four-bit ripple carry adder
'     using the worksheet input values generated by the input module.
'
' Architecture:
'     The routine reads each row of operand bits from the worksheet, performs
'     staged binary addition from least significant bit to most significant
'     bit, and writes the resulting sum bits and final carry-out.
'
'         S0-S3 → sum outputs
'         C4    → final carry-out
'
'     Carry is propagated stage by stage in the same order used by a ripple
'     carry adder. This mirrors the arithmetic behavior of the digital logic
'     implementation and allows the spreadsheet to act as a verification tool.
'
' Inputs:
'     Worksheet columns A-H
'
'         A0-A3 : operand A bits
'         B0-B3 : operand B bits
'
' Outputs:
'     Row 2      : output column labels S0 through C4
'     Rows 3-258 : computed output values for all input combinations
'
' Design Notes:
'     This module exists to generate deterministic expected results for the
'     adder. The worksheet is used as a validation surface rather than as a
'     manually solved exercise, which reduces error and improves repeatability.
'
' Author:      Michael Garcia
' Course:      RBT131 Digital Logic
' Date:        23 Aug 2025
' License:     MIT
'------------------------------------------------------------------------------
Attribute VB_Name = "Outputs"
Public Sub ComputeAdderOutputs()
    Dim i As Long, j As Integer
    Dim A(0 To 3) As Integer, B(0 To 3) As Integer
    Dim S(0 To 3) As Integer, C As Integer
    
    ' Write headers for outputs
    Cells(2, 9).Resize(1, 5).Value = Array("S0", "S1", "S2", "S3", "C4")
    
    ' Loop through all 256 rows
    For i = 0 To 255
        ' Load bits A0-A3 and B0-B3
        For j = 0 To 3
            A(j) = Cells(i + 3, j + 1).Value
            B(j) = Cells(i + 3, j + 5).Value
        Next j
        
        ' Initialize carry
        C = 0
        
        ' Compute sums and propagate carry
        For j = 0 To 3
            S(j) = (A(j) Xor B(j)) Xor C
            C = (A(j) And B(j)) Or (C And (A(j) Xor B(j)))
            Cells(i + 3, 9 + j).Value = S(j) ' Output S0-S3
        Next j
        
        ' Final carry-out
        Cells(i + 3, 13).Value = C ' Output C4
    Next i
End Sub

